"""sensors tables

Revision ID: 09cda088bb39
Revises: 
Create Date: 2024-09-09 18:39:58.453999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09cda088bb39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.String(length=50), nullable=False),
    sa.Column('temperature_engine', sa.Float(), nullable=True),
    sa.Column('tire_pressure', sa.JSON(), nullable=True),
    sa.Column('fuel_level', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_data')
    # ### end Alembic commands ###
